//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public int Idoferta { get; set; }
        public int Idproducto { get; set; }
        public string Descripcion { get; set; }
        public double Porc_dscto { get; set; }
        public System.DateTime Fecha_desde { get; set; }
        public System.DateTime Fecha_Hasta { get; set; }
        public double Precio { get; set; }
        public double PrecioOferta { get; set; }
        public byte[] Fotoproducto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
