//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracion_Oferta
    {
        public int IdValoracion { get; set; }
        public int Idoferta { get; set; }
        public string Rut { get; set; }
        public int Idnotaoferta { get; set; }
        public byte[] Fotooferta { get; set; }
    
        public virtual Nota_Oferta Nota_Oferta { get; set; }
    }
}
